services:
  selenoid1:
    image: aerokube/selenoid:latest-release
    hostname: selenoid1
    networks:
      - selenoid1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dima/selenoid_compose/browsers.json:/etc/selenoid/browsers.json:ro
    command: ["-container-network=selenoid1"]
  selenoid2:
    image: aerokube/selenoid:latest-release
    hostname: selenoid2
    networks:
      - selenoid2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dima/selenoid_compose/browsers.json:/etc/selenoid/browsers.json:ro
    command: ["-container-network=selenoid2"]
    
  selenoid_ui:
    image: aerokube/selenoid-ui:1.10.11
    networks:
      - selenoid1
    ports:
      - "8080:8080"
    depends_on: ["ggr_ui"]
    command: ["--selenoid-uri", "http://ggr_ui:8888"]   

  ggr: 
    image: aerokube/ggr:1.7.2
    hostname: ggr
    depends_on: ["selenoid1", "selenoid2"]
    networks:
      - selenoid1
    volumes:
      - /home/dima/selenoid_compose/ggr/grid-router/:/etc/grid-router:ro
    command: ["-guests-allowed", "-guests-quota", "test", "-verbose"]

  ggr_ui: 
    image: aerokube/ggr-ui:1.2.0
    hostname: ggr_ui
    depends_on: ["ggr"]
    networks:
      - selenoid1
    ports:
      - "8888:8888"
    volumes:
      - /home/dima/selenoid_compose/ggr/grid-router/quota/:/etc/grid-router/quota:ro
  
  nginx:
    image: nginx
    networks:
      - selenoid1
    depends_on: ["selenoid_ui"]
    volumes:
      - /home/dima/selenoid_compose/nginx/selenoid.conf:/etc/nginx/conf.d/selenoid.conf:ro
    ports:
      - "80:80"
      
networks:
  selenoid1:
    name: selenoid1
  selenoid2:
    name: selenoid2
    
